### ISSUE TITLE
documentation suggestion

### ISSUE THREAD

**Issue by dadaphl** [jkphl/gulp-svg-sprite#27]
gulp.src('**/*.svg', {cwd: 'assets'})

is misleading for a gulp beginner. I thought the cwd:'assets' part is some kind of configuration option. It took me a while to figure out, that that was the reason my images weren't found.
Also the, there is no output from gulp that indicates what it is doing. Hard locate mistakes.

**Comment by jkphl** [comment]
Hey @dadaphl,

thanks for reporting this. Although I understand your concerns — especially because I'm a Gulp beginner myself — I don't really know how to deal with it. What do you suggest?

The line

```javascript
gulp.src('*/.svg', {cwd: 'assets'})
```

strictly isn't part of *gulp-svg-sprite* at all. I think it's beyond *gulp-svg-sprite*'s scope to explain the way of [globbing in gulp](https://github.com/gulpjs/gulp/blob/master/docs/API.md#gulpsrcglobs-options) — that knowledge should be seen as a pre-requisite. IMO it's rather important to showcase that there **is** the `cwd` option for `gulp.src()`, as omitting it in the documentation would surely provoke another documentation suggestion ...

Do you think changing `"assets"` to `"path/to/assets"` and / or adding a hint to Gulp's globbing options would improve the situation?

Thanks & cheers,
Joschi

**Comment by jkphl** [comment]
As you didn't feedback anymore, I modified the documentation as suggested and will close this issue now. Please feel free to re-open it in case of further problems.
