### ISSUE TITLE
Why do some fills get removed?

### ISSUE THREAD

**Issue by nathanjessen** [jkphl/gulp-svg-sprite#58]
Most svg fills remain as-is when they get added to an svg-sprite but for some reason if the fill is 000 or 000000, the fill attribute gets removed from the svg in the resulting svg-sprite. Why does this happen? Is there a config option to override this behavior?

**Comment by jkphl** [comment]
I'm pretty sure the reason is one of SVGO's more aggressive plugins — see [here](https://github.com/jkphl/svg-sprite/blob/master/docs/configuration.md#pre-defined-shape-transformation-with-custom-configuration-object-values) for getting an idea how to disable them selectively, and [here](https://github.com/jkphl/svg-sprite/blob/master/lib/svg-sprite/transform/svgo.js#L16) for a list of SVGO's plugins — or because you exported your SVGs with Illustrator and didn't specify "presentation attributes" during export (please have a look at [this thread](https://github.com/jkphl/svg-sprite/issues/96#issuecomment-112903315)). Please let me know if you can solve your case with this.

**Comment by brianfeister** [comment]
@nathanjessen curious if you made progress on this. Due to semver in my build, this bit me and borked my production spritemap, my project also has lots of SVG's with `fill="#000000"`

**Comment by nathanjessen** [comment]
@brianfeister haven't had the time or desire to look into it. Our temporary fix was to modify the fill slightly to something like `fill="#000100"`

**Comment by jkphl** [comment]
@brianfeister @nathanjessen Did you try to selectively disable the SVGO plugins as I described above?

**Comment by brianfeister** [comment]
@jkphl looking at it is in my queue of things to do. I was hoping for a quick win if @nathanjessen had the exact config code for me to drop in. I'll certainly update this ticket with the needed config when I get to it in the next week or so.

**Comment by jkphl** [comment]
@brianfeister Cool, thanks! :)

**Comment by jkphl** [comment]
I'll close the issue due to inactivity but if this still an issue for you please feel free to get back to me again!

**Comment by MaciejJanyska** [comment]
@nathanjessen @brianfeister You should try to disable the `removeUnknownsAndDefaults` plugin, which is enabled by default.
