### ISSUE TITLE
timestamp updated in spritesheet.html even when there was no change

### ISSUE THREAD

**Issue by DanielRuf** [jkphl/gulp-svg-sprite#79]
It seems the timestamp in the spritesheet file is updated even when there were no new images or changes in the images.

**Comment by MaximilianUE** [comment]
Having the same problem with a project that worked just fine a few days ago.

This causes a new change for every time I run 'npm install' which is really annoying since the only changing thing are the date parameters.

Been trying it out to change "gulp-svg-sprite": "^1.3.6" inside "package.json" to not use the above versions, but it didn´t seem to fix the problem.

Any idea what could be causing this?

**Comment by DanielRuf** [comment]
I guess this was alwayd the case but we see it now becausr the generated file is not ignored anymore.
