### ISSUE TITLE
Fill/Stroke colors 

### ISSUE THREAD

**Issue by MarcSa** [jkphl/gulp-svg-sprite#81]
Hello,
First of all thank you for your program.

When I run your program to generate a new sprite, this modifies softly the original colors, is there a parameter to avoid changing the color however slight it is in the new sprite?

The modified colors are:
# B2EEFF -> # ACD2E5
# 2B99BF -> # 2F8FB1
# 24A7C5 -> # 2A9BB6

[assets.zip](https://github.com/jkphl/gulp-svg-sprite/files/2004350/assets.zip)
[renderizedsprite.zip](https://github.com/jkphl/gulp-svg-sprite/files/2004352/renderizedsprite.zip)

Thanks for your help

**Comment by jkphl** [comment]
@MarcSa *svg-sprite* itself doesn't modify the SVG source files in any way (except what's necessary for compiling a sprite). I suspect this might be because of a particular SVGO plugin (no idea which one). Please start by disabling SVGO altogether to find out if it's the reason, then try disabling single plugins and let me know if you succeed. Thanks.

**Comment by MarcSa** [comment]
@jkphl, Hi, I've just modified svgo.js from node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js 

![image](https://user-images.githubusercontent.com/5680975/40103657-8372142e-58ee-11e8-876f-25d8e6f04db0.png)

and gulpfile.js with the online configurator

![image](https://user-images.githubusercontent.com/5680975/40104202-fc15c8fc-58ef-11e8-9366-6a60f3c0930b.png)

is it the correct way? Thanks.

**Comment by MarcSa** [comment]
@jkphl Sorry my mistake, just works perfect, thanks for all!
